import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/style.css";
import "@/styles/responsive.css";
// import "@/styles/series.css";
import Footer from "@/components/footer";
import Script from "next/script";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "DongWorld - Streaming Donghua Berkualitas",
    description: "Nonton donghua favoritmu dengan kualitas HD dan subtitle Indonesia",
    type: "website",
    url: "https://dongworld.example.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="keywords" content="donghua, anime china, streaming donghua, watch donghua online" />
        <meta name="author" content="DongWorld Team" />
        <title>DongWorld - Streaming Donghua Berkualitas</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossOrigin="anonymous"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="dl-root">
          <main className="dl-main-content">
          <Navbar />
          <Sidebar />
          {children}
          <Footer />
          <Script src="/js/search.js" strategy="afterInteractive" />
          </main>
        </div>
      </body>
    </html>
  );
}
